import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "../../styles/globals.scss"
// import "styles/global.scss"
import {HeroUIProvider} from "@heroui/react";
import NavComponent from '@/components/nav'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HeroUIProvider>
          <NavComponent/>
          {children}
        </HeroUIProvider>
       
      </body>
    </html>
  );
}
